name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world"
  second-job:
    runs-on: ubuntu-latest
    needs: my-job
    steps:
      - name: my-step2
        run: echo "hello world,again"
    

